export const developers = [
  {
    name: "Hasan Huda",
    description: "Software Engineer",
    github: "https://github.com/hasan-huda",
    linkedin: "https://www.linkedin.com/in/hasan-huda/",
    portfolio: "https://hasan-portfolio-eight.vercel.app",
    image: "/HasanHuda.jpeg",
    technologies: [],
  },
  {
    name: "Omar Ahmed",
    description: "Software Engineer",
    github: "https://github.com/omar-t-ahmed",
    linkedin: "www.linkedin.com/in/omar-ahmed-software-engineer",
    portfolio: "https://www.omarcodes.dev/",
    image: "/OmarAhmed.jpg",
    technologies: [],
  },
  {
    name: "Hasan Huda",
    description: "Software Engineer",
    github: "https://github.com/hasan-huda",
    linkedin: "https://www.linkedin.com/in/hasan-huda/",
    portfolio: "https://hasan-portfolio-eight.vercel.app",
    image: "/HasanHuda.jpeg",
    technologies: [],
  },
  {
    name: "Hasan Huda",
    description: "Software Engineer",
    github: "https://github.com/hasan-huda",
    linkedin: "https://www.linkedin.com/in/hasan-huda/",
    portfolio: "https://hasan-portfolio-eight.vercel.app",
    image: "/HasanHuda.jpeg",
    technologies: [],
  },
];
