export const developers = [
  {
    name: "Hasan Huda",
    description: "Software Engineer",
    github: "https://github.com/hasan-huda",
    linkedin: "https://www.linkedin.com/in/hasan-huda/",
    portfolio: "https://hasan-portfolio-eight.vercel.app",
    image: "/HasanHuda.jpeg",
    technologies: ["NextJS", "Typescript", "Tailwind", "PostgreSQL"],
  },
  {
    name: "Hasan Huda",
    description: "Software Engineer",
    github: "https://github.com/hasan-huda",
    linkedin: "https://www.linkedin.com/in/hasan-huda/",
    portfolio: "https://hasan-portfolio-eight.vercel.app",
    image: "/HasanHuda.jpeg",
    technologies: ["NextJS", "Typescript", "Tailwind", "PostgreSQL"],
  },
  // {
  //   name: "Hasan Huda",
  //   description: "Software Engineer",
  //   github: "https://github.com/hasan-huda",
  //   linkedin: "https://www.linkedin.com/in/hasan-huda/",
  //   portfolio: "https://hasan-portfolio-eight.vercel.app",
  //   image: "/HasanHuda.jpeg",
  //   technologies: ["NextJS", "Typescript", "Tailwind", "PostgreSQL"],
  // },
  // {
  //   name: "Hasan Huda",
  //   description: "Software Engineer",
  //   github: "https://github.com/hasan-huda",
  //   linkedin: "https://www.linkedin.com/in/hasan-huda/",
  //   portfolio: "https://hasan-portfolio-eight.vercel.app",
  //   image: "/HasanHuda.jpeg",
  //   technologies: ["NextJS", "Typescript", "Tailwind", "PostgreSQL"],
  // },
];
