export const developers = [
  {
    name: "Hasan Huda",
    description: "Software Engineer",
    github: "https://github.com/hasan-huda",
    linkedin: "https://www.linkedin.com/in/hasan-huda/",
    portfolio: "https://hasan-portfolio-eight.vercel.app",
    image: "/HasanHuda.jpeg",
    technologies: [],
  },
  {
    name: "Omar Ahmed",
    description: "Software Engineer",
    github: "https://github.com/omar-t-ahmed",
    linkedin: "https://www.linkedin.com/in/omar-ahmed-software-engineer",
    portfolio: "https://www.omarcodes.dev/",
    image: "/OmarAhmed.jpg",
    technologies: [],
  },
  {
    name: "Saqif Abedin",
    description: "Software Engineer",
    github: "https://github.com/Saqif-Abedin",
    linkedin: "https://www.linkedin.com/in/saqifabedin/",
    portfolio: "https://saqif-abedin.github.io/",
    image: "/SaqifAbedin.jpg",
    technologies: [],
  },
  {
    name: "Taha Khan",
    description: "Software Engineer",
    github: "https://github.com/tkhan271828",
    linkedin: "https://www.linkedin.com/in/taha-khan1",
    portfolio: "https://tahkhan123.github.io/landing-page/",
    image: "/TahaKhan.jpg",
    technologies: [],
  },
];
